# Generated by Django 4.1.3 on 2022-12-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_artist_birth_date_alter_artist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='title',
            field=models.CharField(max_length=60, unique=True, verbose_name='Title'),
        ),
    ]
