# Generated by Django 4.1.3 on 2022-12-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_play_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
