# Generated by Django 4.1.3 on 2022-12-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_play_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='play',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='play',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
