# Generated by Django 4.1.3 on 2022-12-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_news_date_alter_news_time_alter_play_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='artist',
            name='birth_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Birth Date'),
        ),
    ]
